---
apiVersion: polixy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: emojivoto
  name: voting-grpc
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: voting
    app.kubernetes.io/version: v11
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
      app.kubernetes.io/name: voting
  port: grpc
  proxyProtocol: gRPC
---
apiVersion: polixy.linkerd.io/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: emojivoto
  name: voting-grpc
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: voting
    app.kubernetes.io/version: v11
spec:
  server:
    name: voting-grpc
  # The voting service only allows requests from the web service.
  client:
    meshTLS:
      serviceAccounts:
        - name: web
